<br/><br/>
<?php $this->headTitle('User Login'); ?>

<div id="wrapper_login">
<div id="menu">
    <div id="left"></div>
    <div id="right"></div>
    <h2>User Login</h2>
    <div class="clear"></div>
</div>
<div id="desc">
    <div class="body">
        <div class="col w10 last bottomlast">
<?php
    echo $this->form->setAction($this->url());    
?>          
    
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <div id="body_footer">
        <div id="bottom_left"><div id="bottom_right"></div></div>
    </div>
</div>
</div>