<br />
<a href="
	<?php echo $this->url(array('controller' => 'muser', 'action' => 'add'),Null,True);?>
	" class="button"><span>Create New User</span>
</a>
<br /><br />

<a href="
	<?php echo $this->url(array('controller' => 'muser', 'action' => 'edit'),Null,True);?>
	" class="button"><span>Edit Existing User</span>
</a>
<br /><br />

<a href="
	<?php echo $this->url(array('controller' => 'muser', 'action' => 'del'),Null,True);?>
	" class="button"><span>Delete User</span>
</a>
<br /><br />


