<div id="view-content">
	<?php if ( ! ($this->error) && $this->paginator): ?>
	<?php if (count($this->paginator)): ?>
	<dl><?php foreach ($this->paginator as $entry): ?>
	<div class="col w8"><div class="content">
	<span class="strong"><?php echo $entry['package'] ?></span><br/>
    <span class="italic"><?php echo $entry['description'] ?></span></div></div>
	<div class="col w1"><div class="content">
    <a href="/pkgdetails/index/package/<?php echo $entry['package'] ?>" class="button green"><span>Details</span></a></div></div>
	<div class="col w1 last"><div class="content">
    <a href="/pkginstall/index/package/<?php echo $entry['package'] ?>" class="button yellow"><span>Install</span></a></div></div>
    <?php endforeach ?>
    <?php endif ?>
    <?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'partials/paginator.phtml'); ?>
	<?php else: ?>
	<span class="strong"><?php echo $this->error ?></span>
	<?php echo $this->addButton('back','/softcenter/pkgsearch') ?>
	<?php echo $this->addButton('ok') ?>
	<?php endif ?>
</dl>
</div>
