
<?php
global $result;
#$soft_id = $this->result['soft_id'];
$size = number_format( $this->result['size']/1024);
$installed_size = number_format( $this->result['installed_size']);
?>
</br><b>
<?php echo $this->result['package'] ?></b></br>
<?php echo $this->result['description'] ?></br></br>
<?php echo $this->result['desc_more'] ?></br></br></br><b>
<div class="col w7"><div class="content">
<?php echo "size:</b> {$size} kB" ?></br><b>
<?php echo "installed size:</b> {$installed_size} kB" ?></br><b>
<?php echo "version:</b> {$this->result['version']}" ?></br><b>
<?php echo "source:</b> {$this->result['source']}" ?></br><b>
<?php echo "maintainer:</b> {$this->result['maintainer']}" ?></br><b>
<?php echo "home page:</b> <a href='{$this->result['homepage']}' target=\"_blank\"><i>{$this->result['homepage']}</i></a>"?>
</br></br>

<?php if ($this->status) : ?>
<a href="/pkginstall/index/package/<?php echo $this->result['package'] ?>" class="button green"><span>Install Package</span></a></div></div>
<?php else :?>
<a href="/pkgrequest/index/package/<?php echo $this->result['package'] ?>" class="button red"><span>Request Package</span></a></div></div>
<?php endif ?>
</div>
<div class="col w3 last"><div class="content">
<?php echo "<a href=\"http://screenshots.debian.net/screenshot/{$this->result['package']}\"
 target=\"_blank\"><img src=\"http://​screenshots.debian.net/thumbnail/{$this->result['package']}\" alt=\"Screenshot\"></a>" ?>
</div>

