<br/><br/>
<div class="col w10 last">
    <div class="content">
        <div class="shelf">
            <div class="left"></div>
            <div class="right"></div>
            <div class="inside">
                <div class="books">
                    <div class="col w2">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'misc')); ?>">
                            <span>Accessories</span>
                            <img src="images/dept/accessories.png" alt="" />
                        </a>
                    </div>
                    <div class="col w2">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'devel')); ?>">
                            <span>Developer Tools</span>
                            <img src="images/dept/developer-tools.png" alt="" />
                        </a>
                    </div>
                    <div class="col w2">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'math')); ?>">
                            <span>Education</span>
                            <img src="images/dept/education.png" alt="" />
                        </a>
                    </div>
                    <div class="col w2 last">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'editors')); ?>">
                            <span>Editors</span>
                            <img src="images/dept/fonts.png" alt="" />
                        </a>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="shelf">
            <div class="left"></div>
            <div class="right"></div>
            <div class="inside">
                <div class="books">
                    <div class="col w2">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'games')); ?>">
                            <span>Games</span>
                            <img src="images/dept/games.png" alt="" />
                        </a>
                    </div>
                    <div class="col w2">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'graphics')); ?>">
                            <span>Graphics</span>
                            <img src="images/dept/graphics.png" alt="" />
                        </a>
                    </div>
                    <div class="col w2">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'web')); ?>">
                            <span>Internet</span>
                            <img src="images/dept/internet.png" alt="" />
                        </a>
                    </div>
                    <div class="col w2 last">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'editors')); ?>">
                            <span>Office</span>
                            <img src="images/dept/office.png" alt="" />
                        </a>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="shelf">
            <div class="left"></div>
            <div class="right"></div>
            <div class="inside">
                <div class="books">
                    <div class="col w2">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'science')); ?>">
                            <span>Science & Engineering</span>
                            <img src="images/dept/science-engineering.png" alt="" />
                        </a>
                    </div>
                    <div class="col w2">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'sound')); ?>">
                            <span>Sound & Video</span>
                            <img src="images/dept/sound-video.png" alt="" />
                        </a>
                    </div>
                    <div class="col w2">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'gnome')); ?>">
                            <span>Themes & Tweaks</span>
                            <img src="images/dept/themes-tweaks.png" alt="" />
                        </a>
                    </div>
                    <div class="col w2 last">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'localization')); ?>">
                            <span>Localization</span>
                            <img src="images/dept/universal-access.png" alt="" />
                        </a>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>


    </div>
    <div class="clear"></div>
</div>
