<?php
$this->title = "Package info";
$this->headTitle($this->title);
?>
<br/><br/>
<?php if($this->selpackage) : ?>
    <h3><?php echo "Package : " . htmlentities($this->selpackage); ?></h3>
        <br/>
        <a class="navi_btn" href="<?php echo $this->url(array('controller'=>'cat', 'action'=>'index'));?>">&lt; Back to List</a>
        <br/><br/><br/>
        <div class="pkginfo">
            <dl>    
                <dt>In Section : </dt>    
                    <dd><?php echo htmlentities($this->packageRow->section); ?></dd>
                <br/>

                <dt>Description : </dt>    
                    <dd><?php echo htmlentities($this->packageRow->description); ?></dd>
                <br/>       
                <?php if ($this->packageRow->longdescription) : ?>
                        <dd><?php echo htmlentities($this->packageRow->longdescription); ?></dd>
                    <br/>
                <?php endif; ?>

                <dt>Architecture : </dt>    
                    <dd><?php echo htmlentities($this->packageRow->architecture); ?></dd>
                <br/>

                <?php if ($this->packageRow->version) : ?>
                    <dt>Version : </dt>    
                        <dd><?php echo htmlentities($this->packageRow->version); ?></dd>
                    <br/>
                <?php endif; ?>

                <?php if ($this->packageRow->size) : ?>
                    <dt>Size : </dt>    
                        <dd><?php echo htmlentities($this->packageRow->size); ?></dd>
                    <br/>
                <?php endif; ?>

                <?php if ($this->packageRow->installedsize) : ?>
                    <dt>Installed-size : </dt>    
                        <dd><?php echo htmlentities($this->packageRow->installedsize); ?></dd>
                    <br/>
                <?php endif; ?>

                <?php if ($this->packageRow->maintainer) : ?>
                    <dt>Maintainer : </dt>    
                        <dd><?php echo htmlentities($this->packageRow->maintainer); ?></dd>
                    <br/>
                <?php endif; ?>

                <?php if ($this->packageRow->homepage) : ?>
                    <dt>Home Page :</dt>
                        <dd><a href="<?php echo htmlentities($this->packageRow->homepage); ?>"><?php echo htmlentities($this->packageRow->homepage);?></a></dd>
                    <br/>
                <?php endif; ?>
            </dl>
        </div>
<?php endif; ?>
<!-- When a package is not selected -->
<?php if(!$this->selpackage) : ?>
    <h4>You haven't selected a Package !!</h4>
    <br/>
        <a class="navi_btn" href="#">&lt; Back to List</a>
<?php endif; ?>   

    