<?php $paginationControl = $this->paginationControl($this->paginator, 'All', 'partials/paginator.phtml') ?>

<div class="pagination-control">
    <?php echo $paginationControl ?>
</div>

<div class="paged-data">
    <?php if (count($this->paginator)) : ?>
    <table class="data">
        <thead>
            <tr>
                <th>Available Packages</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            echo $this->partialLoop('partials/categories/pkglistRow.phtml', $this->paginator);
        ?>
        </tbody>
    </table>

    <?php else : ?>

    <div class="notice">
        <p >No items found</p>
    </div>

    <?php endif ?>
</div>

<div class="pagination-control">
    <?php echo $paginationControl ?>
</div>
