<br/>
<a href="
	<?php echo $this->url(array('controller' => 'team', 'action' => 'adduser'),Null,True);?>
	" class="button"><span>Add New User</span>
</a>
<br /><br />

<a href="
	<?php echo $this->url(array('controller' => 'team', 'action' => 'deluser'),Null,True);?>
	" class="button"><span>Delete Existing User</span>
</a>
<br /><br />
<a href="
	<?php echo $this->url(array('controller' => 'team', 'action' => 'addpackage'),Null,True);?>
	" class="button"><span>Allow Software</span>
</a>
<br /><br />

<a href="
	<?php echo $this->url(array('controller' => 'team', 'action' => 'delpackage'),Null,True);?>
	" class="button"><span>Deny Software</span>
</a>
<br /><br />
<?php echo $this->addButton('home') ?>



