<br />
<a href="
	<?php echo $this->url(array('controller' => 'mteam', 'action' => 'add'),Null,True);?>
	" class="button"><span>Create New Team</span>
</a>
<br /><br />

<a href="
	<?php echo $this->url(array('controller' => 'mteam', 'action' => 'edit'),Null,True);?>
	" class="button"><span>Edit Existing Team</span>
</a>
<br /><br />

<a href="
	<?php echo $this->url(array('controller' => 'mteam', 'action' => 'del'),Null,True);?>
	" class="button"><span>Delete Team</span>
</a>
<br /><br />

