 <?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('VOS Software Portal');
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
   
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/login.css'); ?>
    
    <?php echo $this->headLink(); ?>
</head>
    <body>
        <h1>VOS Software Portal</h1>
        <div class="container">
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>