 <?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('VOS Software Portal');
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/gray_admin/css/reset.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/gray_admin/css/style.css'); ?>
    
    <?php echo $this->headLink(); ?>
</head>
    <body>       
        <?php echo $this->layout()->content; ?>
    </body>
</html>
