 <?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('VOS Software Portal');
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery/jquery-1.7.2.min.js'); ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jqueryui/jquery-ui-1.8.21.custom.min.js'); ?>
    
    <?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/blueprint/screen.css','screen, projection'); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/main.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/blueprint/ie.css','screen, projection','IE'); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/blueprint/print.css','print'); ?>
    <?php $this->headLink()->appendStylesheet('/css/smoothness/jquery-ui-1.8.21.custom.css'); ?>
    
    <?php echo $this->headLink(); ?>

</head>
    <body>
        <div id="header0">
            <div id="logged-in-as"><?php echo $this->loggedInAs(); ?></div>
            <a href="#" id="getNotice">Notifications</a>
            <div id="notices"></div>
        </div>
        <div id="banner"></div>             
        <div class="topnav">
            <!-- includes a <ul class = navigation >   -->
            <?php echo $this->navigation()->menu(); ?>            
        </div>  
        <div class="container">
            <div class="push-2 span-12 maincontent">                            
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>
