 <?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('VOS Software Portal');
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <base href="<?php echo $this->serverUrl(), $this->baseUrl() ?>/"></base>
    <?php echo $this->headTitle(); ?>   
   
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/cristalx/css/main.css','screen, projection'); ?>    
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/cristalx/css/print.css','print'); ?>

    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/blueprint/ie.css','screen, projection','IE'); ?>   

    <?php $this->headLink()->appendStylesheet('/css/paginator/light-theme.css'); ?>
    <?php echo $this->headLink(); ?>

</head>
<body>
        <div id="header0">
            <div id="logged-in-as"><?php echo $this->loggedInAs(); ?></div>
            <a href="#" id="getNotice">Notifications</a>            
        </div>

<!-- Main -->
<div id="main" class="box">

    <!-- Header -->
    <div id="header">

        <!-- Logotyp -->
        <h1 id="logo"><a href="./" title="CrystalX [Go to homepage]"><strong>V</strong>OS Software Portal<span></span></a></h1>
        <hr class="noscreen" />

        <!-- Quick links -->
        <div class="noscreen noprint">
            <p><em>Quick links: <a href="#content">content</a>, <a href="#tabs">navigation</a>, <a href="#search">search</a>.</em></p>
            <hr />
        </div>

        <!-- Search -->
        <div id="search" class="noprint">
            <form action="" method="get">
                <fieldset><legend>Search</legend>
                    <label><span class="noscreen">Find:</span>
                    <span id="search-input-out"><input type="text" name="" id="search-input" size="30" /></span></label>
                    <input type="image" src="design/search_submit.gif" id="search-submit" value="OK" />
                </fieldset>
            </form>
        </div> <!-- /search -->

    </div> <!-- /header -->

     <!-- Main menu (tabs) -->
     <div id="tabs" class="noprint">

            <h3 class="noscreen">Navigation</h3>
            <ul class="box">
                <li><a href="#">Index<span class="tab-l"></span><span class="tab-r"></span></a></li>
                <li id="active"><a href="#">Weblog<span class="tab-l"></span><span class="tab-r"></span></a></li> <!-- Active -->
                <!-- includes a <ul class = navigation >   -->
                <?php echo $this->navigation()->menu(); ?>
            </ul>

        <hr class="noscreen" />
     </div> <!-- /tabs -->

    <!-- Page (2 columns) -->
    <div id="page" class="box">
    <div id="page-in" class="box">

        <div id="strip" class="box noprint">

            <!-- RSS feeds -->
            <p id="rss"><strong>RSS:</strong> <a href="#">featurettes</a> / <a href="#">updates</a></p>
            <hr class="noscreen" />

            <!-- Breadcrumbs -->
            <p id="breadcrumbs">You are here: <a href="#">Home</a> &gt; <a href="#">Category</a> &gt;  <strong>Page</strong></p>
            <hr class="noscreen" />

        </div> <!-- /strip -->

        <!-- Content -->
        <div id="content">

        <div class="maincontent">
            <?php echo $this->layout()->content; ?>
        </div>
        <br/><br/>           

        </div> <!-- /content -->

        <!-- Right column -->
        <div id="col" class="noprint">
            <div id="col-in">

                

                <!-- Category -->
                <h3 ><span>Category</span></h3>

                <ul id="category">
                    <li id="category-active"><a href="#">Selected category</a></li> <!-- Active -->
                    <li><a href="#">Category</a></li>
                    <li><a href="#">Category</a></li>
                    <li><a href="#">Category</a></li>
                    <li><a href="#">Category</a></li>
                </ul>

                <hr class="noscreen" />
                
                <!-- Links -->
                <h3><span>Links</span></h3>

                <ul id="links">
                    <li><a href="#">Something</a></li>
                    <li><a href="#">Something</a></li>
                    <li><a href="#">Something</a></li>
                    <li><a href="#">Something</a></li>
                    <li><a href="#">Something</a></li>
                </ul>

                <hr class="noscreen" />

            </div> <!-- /col-in -->
        </div> <!-- /col -->

    </div> <!-- /page-in -->
    </div> <!-- /page -->

    <!-- Footer -->
    <div id="footer">
        <div id="top" class="noprint"><p><span class="noscreen">Back on top</span> <a href="#header" title="Back on top ^">^<span></span></a></p></div>
        <hr class="noscreen" />

        <p id="createdby">created by <a href="http://www.nuvio.cz">Nuvio | Webdesign</a> <!-- DON´T REMOVE, PLEASE! --></p>
        <p id="copyright">&copy; 2012 <a href="mailto:my@mail.com">Delta</a></p>
    </div> <!-- /footer -->

</div> <!-- /main -->

</body>
</html>
<?php /*

     <!-- includes a <ul class = navigation >   -->
     <?php echo $this->navigation()->menu(); ?>
    

        <hr class="noscreen" />
     </div> <!-- /tabs -->

        <div class="container">
            <div class="maincontent">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
 */ ?>
 