 <?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('VOS Software Portal');
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>      
</head>
<body bgcolor="#e5ecf9">
        <div class="container">
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>