 <?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('VOS Software Portal');
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
        
    <?php $this->headScript()->appendFile($this->baseUrl().'/js/jquery/jquery-1.7.2.min.js'); ?>    
    <?php $this->headScript()->appendFile($this->baseUrl().'/gray_admin/js/global.js'); ?>
    <?php $this->headScript()->appendFile($this->baseUrl().'/gray_admin/js/modal.js'); ?>
    <?php echo $this->headScript(); ?>

    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/gray_admin/css/style.css','screen, projection'); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/paginator/light-theme.css') ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/blueprint/grid.css') ?>    
    <?php echo $this->headLink(); ?>
    <link rel="shortcut icon" href="images/vir.ico">
</head>
    <body>
<!-- Layout Header --><!-- Layout Header --><!-- Layout Header --><!-- Layout Header -->
        <div id="header">
            <div class="col w5 bottomlast">
                    <a href="" class="logo">
                            <img src="/gray_admin/images/logo.gif" alt="Logo"/>
                    </a>
            </div>
            <div class="col w5 last right bottomlast">
                <?php echo "user" #TODO echo $this->loggedInAs(); ?>
            </div>
            <div class="clear"></div>            
        </div>
<!-- Layout Header --><!-- Layout Header --><!-- Layout Header --><!-- Layout Header -->
<br/><br/>
<!-- Layout Wrapper --><!-- Layout Wrapper --><!-- Layout Wrapper --><!-- Layout Wrapper -->
        <div id="wrapper">
            <div id="minwidth">
                <div id="holder">
    <!-- Menu --><!-- Menu --><!-- Menu --><!-- Menu --><!-- Menu -->
                    <div id="menu">
                        <div id="left"></div>
                        <div id="right"></div>
                        <!-- has a <ul class = navigation >   -->
                    <?php echo $this->navigation()->menu(); ?>
                    <!--
                        <ul>
                            <li>
                                <a href="index.html" class="selected"><span>Help</span></a>
                            </li>
                            <li>
                                <a href="users.html"><span>Users</span></a>
                            </li>
                            <li>
                                <a href="articles.html"><span>Articles</span></a>
                            </li>
                        </ul>
                    -->
                        <div class="clear"></div>
                    </div>
    <!-- Menu --><!-- Menu --><!-- Menu --><!-- Menu --><!-- Menu -->

    <!-- Sub Menu --><!-- Sub Menu --><!-- Sub Menu --><!-- Sub Menu -->
            <?php echo $this->partial('partials/submenu.phtml'); ?>
    <!-- Sub Menu --><!-- Sub Menu --><!-- Sub Menu --><!-- Sub Menu -->

        <!-- Layout Body --><!-- Layout Body --><!-- Layout Body --><!-- Layout Body --><!-- Layout Body -->
                    <div id="desc">
                        <div class="body">                            
                            <div id="messages"></div>
                            <div class="clear"></div>
                            
                            <div class="push maincontent">
                                <?php echo $this->layout()->content; ?>                                                              
                            </div>

            <!-- Layout bottom --><!-- Layout bottom --><!-- Layout bottom --><!-- Layout bottom -->
                        <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
                        <div id="body_footer">
                            <div id="bottom_left"><div id="bottom_right"></div></div>
                        </div>
                    </div>
        <!-- Layout Body --><!-- Layout Body --><!-- Layout Body --><!-- Layout Body --><!-- Layout Body -->
                </div>
            </div>
        </div>
<!-- Layout Wrapper --><!-- Layout Wrapper --><!-- Layout Wrapper --><!-- Layout Wrapper -->
        <div id="footer">
            <p class="last">Copyright 2009 - Gray Admin Template - Created by <a href="">Passatgt</a></p>
        </div>
    </body>
</html>
