<br />
<a href="
	<?php echo $this->url(array('controller' => 'mpackage', 'action' => 'addbyjob'),Null,True);?>
	" class="button"><span>Allow Packages by Job Type</span>
</a>
<br /><br />

<a href="
	<?php echo $this->url(array('controller' => 'mpackage', 'action' => 'delbyjob'),Null,True);?>
	" class="button"><span>Deny Packages by Job Type</span>
</a>
<br /><br />

<a href="
	<?php echo $this->url(array('controller' => 'mpackage', 'action' => 'addbyteam'),Null,True);?>
	" class="button"><span>Allow Packages by Team Type</span>
</a>

<br /><br />
<a href="
	<?php echo $this->url(array('controller' => 'mpackage', 'action' => 'delbyteam'),Null,True);?>
	" class="button"><span>Deny Packages by Team Type</span>
</a>
<br /><br />
