<br/><br/>
<!-- start column block --><!-- start column block --><!-- start column block -->
<div id="table" class="help">
    <div class="col w10 last">
        <div class="content">
            <h1>All Sections</h1>            
            <?php $this->inlineScript()->appendFile($this->baseUrl().'/js/paginator/paginator.js') ?>
            <div id="paged-data-container">
                <?php echo $this->render('sect/index.ajax.phtml') ?>
            </div>
            <?php echo $this->inlineScript()
                            ->prependFile($this->baseUrl().'/js/paginator/modernizr-1.7.min.js')
                            ->prependFile($this->baseUrl().'/js/jquery-1.7.2.min.js') ; ?>
        </div>
    </div>
    <div class="clear"></div>
</div>
<!-- end column block --><!-- end column block --><!-- end column block -->

