<!-- Script for Ajax calls -->
<script type="text/javascript">
$(function()
{
    $('#getpkgLink').click(function()
    {
        getPkgJson('admin');
        return false;
    });

    $('#searchLink').click(function()
    {
        findPkgJson($("#tbSearch").val());
        return false;
    });

});

function getPkgJson(section)
{
    $.post(
        "async/getinfo",
        {
            "section" : section
        },
        function(data)
        {
            //alert(data);

            for (var i=0; i< data.length; i++)
            {
             $("#packageList").append("<h6>"+data[i].package+"</h6>");
            }
        },'json'
    );
}

function findPkgJson(name)
{
    $.post(
        "async/searchpkg",
        {
            "name" : name
        },
        function(data)
        {
            //alert(data);
            for (var i=0; i< data.length; i++)
            {
             $("#searchResults").append("<h6>"+data[i].package+"</h6>");
            }
        },'json'
    );
}

</script>
<script type="text/javascript">
    $(function()
    {
        $('#getsec').click(function()
        {
            $.post(
                "async/getsec",
                {},
                function(data)
                {
                    for (var i=0; i< data.length; i++)
                    {
                        $("#sections").append("<li>"+data[i].section+"</li>");                
                    }                    
                },'json'

            );  

            return false;         

        });

    });

</script>