
<div class="module buttons">
    <a href="" class="dropdown_button"><small class="icon clipboard"></small><span>Administrative Tasks</span></a>
    <div class="dropdown help_index" style="width : 350px;">
        <div class="arrow"></div>
        <div class="content">
            <div class="col w10">
            <?php if ($this->isAdmin()) : ?>
                <a href="<?php echo $this->url(array('controller' => 'adduser')); ?>">
                    Add New User
                    <span>Add new user to virtusa Management Portal</span>
                </a>
                <hr/>                        
                <a href="<?php echo $this->url(array('controller' => 'deluser')); ?>">
                    Delete User
                    <span>Delete an exsisting user</span>
                </a>
                <hr/>                        
                <a href="<?php echo $this->url(array('controller' => 'createteam')); ?>">
                    Create New Team
                    <span>Delete an exsisting team</span>
                </a>
                <hr/>                        
                <a href="<?php echo $this->url(array('controller' => 'delteam')); ?>">
                    Delete Team
                    <span>Create new team to customize user authorizations</span>
                </a>
                <hr/>
                <a href="<?php echo $this->url(array('controller' => 'softreport')); ?>">
                    User Package Tracker
                    <span>View which software installed by each user</span>
                </a> 
                <hr/>
                <a href="<?php echo $this->url(array('controller' => 'requestlog')); ?>">
                    User Requests
                    <span>View requested software</span>
                </a>
            <?php endif?>
            <?php if ($this->isTeamOwner()) : ?>
                <hr/>
                <a href="<?php echo $this->url(array('controller' => 'myteams')); ?>">
                    My Teams
                    <span>Manage teams and related software</span>
                </a>
            <?php endif?>
            </div>
            <div class="clear"></div>
            <a class="button red right close"><small class="icon cross"></small><span>Close</span></a>
            <div class="clear"></div>
        </div>
    </div>
</div>
