
<div class="module buttons">
    <a href="" class="dropdown_button"><small class="icon clipboard"></small><span>Administrative Tasks</span></a>
    <div class="dropdown help_index" style="width : 350px;">
        <div class="arrow"></div>
        <div class="content">
            <div class="col w10">
            <?php if ($this->isAdmin()) : ?>
                <a href="<?php echo $this->url(array('controller' => 'muser'),Null,True); ?>">
                    User-Management
                    <span>Add new user to virtusa Management Portal</span>
                </a>
                <hr/>                        
                <a href="<?php echo $this->url(array('controller' => 'mpackage'),Null,True); ?>">
                    Software-Management
                    <span>Delete an exsisting user</span>
                </a>
                <hr/>                        
                <a href="<?php echo $this->url(array('controller' => 'mteam'),Null,True); ?>">
                    Team-Management
                    <span>Delete an exsisting team</span>
                </a>
                <hr/>
                <a href="<?php echo $this->url(array('controller' => 'softreport'),Null,True); ?>">
                    User Package Tracker
                    <span>View which software installed by each user</span>
                </a> 
                <hr/>
                <a href="<?php echo $this->url(array('controller' => 'request'),Null,True); ?>">
                    User Requests
                    <span>View requested software</span>
                </a>
            <?php endif?>
            <?php if ($this->isTeamOwner()) : ?>
                <hr/>
                <a href="<?php echo $this->url(array('controller' => 'team'),Null,True); ?>">
                    My Teams
                    <span>Manage teams and related software</span>
                </a>
            <?php endif?>
            </div>
            <div class="clear"></div>
            <a class="button right close"><small class="icon cross"></small><span>Close</span></a>
            <div class="clear"></div>
        </div>
    </div>
</div>
