
<div class="module buttons">
    <a href="" class="dropdown_button"><small class="icon clipboard"></small><span>Administrative Tasks</span></a>
    <div class="dropdown help_index" style="width : 350px;">
        <div class="arrow"></div>
        <div class="content">
            <div class="col w10">
                <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'accessories')); ?>">
                    Accessories
                    <span>The template's structure, the basic hierarchy</span>
                </a>
                <hr/>                        
                <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'devel')); ?>">
                    Developer Tools
                    <span>The navigation menu structure</span>
                </a>
                <hr/>
                <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'education')); ?>">
                    Education
                    <span>CSS Files and Structure</span>
                </a>
                <hr/>
                <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'fonts')); ?>">
                    Fonts
                    <span>This template imports three javascript files</span>
                </a>
                <hr/>
                <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'games')); ?>">
                    Games
                    <span>Modules is located below the menu bar, like this</span>
                </a>
                <hr/>
                <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'graphic')); ?>">
                    Graphics
                    <span>Typography options</span>
                </a>                        
            </div>
            <div class="clear"></div>
            <a class="button red right close"><small class="icon cross"></small><span>Close</span></a>
            <div class="clear"></div>
        </div>
    </div>
</div>
