<div id="submenu">
    <div class="modules_left">
        <div class="module buttons">
            <a href="" class="dropdown_button"><small class="icon clipboard"></small><span>App Departments</span></a>
            <div class="dropdown help_index">
                <div class="arrow"></div>
                <div class="content">
                    <div class="col w5">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'accessories')); ?>">
                            Accessories
                            <span>The template's structure, the basic hierarchy</span>
                        </a>
                        <hr/>                        
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'devel')); ?>">
                            Developer Tools
                            <span>The navigation menu structure</span>
                        </a>
                        <hr/>
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'education')); ?>">
                            Education
                            <span>CSS Files and Structure</span>
                        </a>
                        <hr/>
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'fonts')); ?>">
                            Fonts
                            <span>This template imports three javascript files</span>
                        </a>
                        <hr/>
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'games')); ?>">
                            Games
                            <span>Modules is located below the menu bar, like this</span>
                        </a>
                        <hr/>
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'graphic')); ?>">
                            Graphics
                            <span>Typography options</span>
                        </a>                        
                    </div>
                    <div class="col w5 last">
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'internet')); ?>">
                            Internet
                            <span>Basic table with hover option</span>
                        </a>
                        <hr/>                        
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'office')); ?>">
                            Office
                            <span>10 columns, liquid grid system</span>
                        </a>
                        <hr/>
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'science')); ?>">
                            Science & Engineering
                            <span>Three type of messages, success, error and notice</span>
                        </a>
                        <hr/>
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'sound-video')); ?>">
                            Sound & Video
                            <span>Buttons library, with colors and icons</span>
                        </a>
                        <hr/>
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'themes')); ?>">
                            Themes & Tweaks
                            <span>Great looking shelf system for content display</span>
                        </a>
                        <hr/>
                        <a href="<?php echo $this->url(array('controller' => 'cat', 'action' => 'index', 'id' => 'universal')); ?>">
                            Universal Access 
                            <span>Sytlish form with custom checkbox</span>
                        </a>                       
                    </div>
                    <div class="clear"></div>
                    <a class="button right close"><small class="icon cross"></small><span>Close</span></a>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <div>
        	<?php if ($this->isAdmin() or $this->isTeamOwner()) : ?>
        		<?php echo $this->partial('partials/adminmenu.phtml'); ?>
        	<?php endif?>
        </div>        
    </div>
    <div class="title">
        VOS Software Portal
    </div>
    <div class="modules_right">
        <div class="module search">
            <form action="/pkgsearch"method="post">
                <p><input type="text" value="Search..." name="package" /></p>
            </form>
        </div>
    </div>
</div>
