<br/>
<?php foreach ($this->paginator as $entry): ?>
<div class="col w8"><div class="content">
<span class="strong"><h1><?php echo $entry['name'] ?></h1></span>
<span class="italic"><h4><?php echo $entry['job_type'] ?></h4></span></div></div>
<div class="col w2 last"><div class="content">
<a href="/addteamuser/add/name/<?php echo $entry['name'] ?>" class="button yellow"><span>Select</span></a></div></div>
<?php endforeach ?>
<?php echo $this->paginationControl($this->paginator,
                                'Sliding',
                                'partials/paginator.phtml'); ?>
